version: '3'

services:
  fastapi:
    build: api/
    ports:
      - 8080:8080
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: app/
    depends_on:
      - fastapi
    ports:
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge
